# Generated by Django 5.0.4 on 2024-06-03 17:32

import jsonfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_completed_quizes'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='completed_quizes',
            field=jsonfield.fields.JSONField(default=[], null=True, verbose_name='completed_quizes'),
        ),
    ]
